packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.22.18
  "@platforma-sdk/ui-vue": ^1.22.52
  "@platforma-sdk/workflow-tengo": ^2.9.9
  "@platforma-sdk/block-tools": ^2.5.7
  "@platforma-sdk/test": ^1.22.5
  "@platforma-sdk/tengo-builder": ^1.17.5
  "@platforma-sdk/package-builder": ^2.15.6
  "@platforma-sdk/eslint-config": ^1.0.1

  "@platforma-open/milaboratories.software-small-binaries": ^1.15.6
  "@platforma-open/babraham.software-fastqc": ^1.0.10


  "@milaboratories/graph-maker": ^1.1.32

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  'ag-grid-enterprise': &ag-grid ^33.0.4
  'ag-grid-vue3': *ag-grid

  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  
  "typescript": ^5.7.2
  "tsup": ~8.3.5
  "turbo": ^2.5.2

  "vite": ^6.0.7
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "unzipper": "^0.12.3"
  "@changesets/cli": ^2.29.2
