packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.43.2
  "@platforma-sdk/ui-vue": ^1.43.2
  "@platforma-sdk/workflow-tengo": ^5.6.2
  "@platforma-sdk/block-tools": ^2.6.21
  "@platforma-sdk/test": ^1.44.7
  "@platforma-sdk/tengo-builder": ^2.3.0
  "@platforma-sdk/package-builder": ^3.8.1
  "@platforma-sdk/eslint-config": ^1.1.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  "@platforma-open/milaboratories.software-small-binaries": ^1.15.23
  "@platforma-open/babraham.software-fastqc": ^1.0.12
  "@milaboratories/software-pframes-conv": ^2.2.7


  "@milaboratories/graph-maker": ^1.1.157

  "@platforma-open/milaboratories.runenv-python-3": ^1.7.5
  
  'ag-grid-enterprise': &ag-grid ^34.2.0
  'ag-grid-vue3': *ag-grid

  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  '@vueuse/core': ^13.6.0
  
  "typescript": ^5.7.2
  "tsup": ~8.3.5
  "turbo": ^2.5.2

  "vite": ^6.0.7
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "unzipper": "^0.12.3"
  "@changesets/cli": ^2.29.2
